# Generated by Django 4.2.1 on 2023-06-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exemple_personnels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prenom', models.CharField(max_length=50)),
                ('Nom', models.CharField(max_length=50)),
                ('Postnom', models.CharField(max_length=50, null=True)),
                ('Sexe', models.CharField(max_length=1, null=True)),
                ('Date_de_naissance', models.DateField(null=True)),
                ('Numero_de_telephone', models.CharField(max_length=20, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Statut_id', models.IntegerField()),
                ('Fonction_id', models.IntegerField()),
                ('Affectation_id', models.IntegerField()),
            ],
        ),
    ]
